Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
AllCops:
  Exclude:
    - 'spec/**/*.rb'
ClassLength:
  Max: 250
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10